FROM python:3.6
ADD . /
WORKDIR /

COPY requirements.txt requirements.txt
# RUN pip install --upgrade setuptools
RUN pip install -r requirements.txt




# ENTRYPOINT ["/runserver.sh"]
CMD ["python", "app.py"]
